services:
  db:
    image: mysql:8.0
    container_name: app-mysql
    env_file:
      - ./Backend/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/db_inventory.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: ./Backend
    container_name: backend-inventory
    env_file:
      - ./Backend/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/inventory-frontend
    container_name: frontend-inventory
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
