spring.application.name=inventory

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


# Use column names exactly as defined in @Column(name = "..."), no snake_case conversion
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
